version: "3"
services:
  mysql:
    build: ./vm/mysql
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./vm/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./vm/mysql/conf.d:/etc/mysql/conf.d
      - ./vm/log/mysql:/var/log/mysql
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: hoge
      MYSQL_DATABASE: geing
      MYSQL_USER: aratasato
      MYSQL_PASSWORD: hoge
  server:
    build:
      context: ./
      dockerfile: ./vm/server/Dockerfile
    ports:
      - "8080:9090"
    volumes:
      - .:/go/src/github.com/aratasato/geing-server
volumes:
  mysql-data:
