version: "3"
services:
  mysql:
    build: ./mysql
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: geing
      MYSQL_USER: aratasato
      MYSQL_PASSWORD: 0000
