version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
        environment:
          - GO111MODULE: "on"
    working_directory: /go/src/github.com/aratasato/geing-server
    steps:
      - checkout
      - run: go build
workflows:
  version: 2
  build:
    jobs:
      - build